# Generated by Django 5.2.7 on 2025-11-23 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ejerciciorutina',
            name='descanso',
            field=models.FloatField(default=1.5),
        ),
    ]
