# Generated by Django 5.1.3 on 2026-01-06 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gym", "0002_alter_ejerciciorutina_descanso"),
    ]

    operations = [
        migrations.AddField(
            model_name="serieejercicio",
            name="rpe",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (1, "1"),
                    (2, "2"),
                    (3, "3"),
                    (4, "4"),
                    (5, "5"),
                    (6, "6"),
                    (7, "7"),
                    (8, "8"),
                    (9, "9"),
                    (10, "10"),
                ],
                null=True,
                verbose_name="RPE (1=fácil, 10=fallo)",
            ),
        ),
    ]
